compose added

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,3 +1,4 @@
+name: 🚀 LLMOps Watcher CI
 
 on:
   push:
@@ -11,12 +12,16 @@ jobs:
       - name: 📥 Checkout code
         uses: actions/checkout@v3
 
+      - name: 🧪 Debug local files
+        run: |
+          echo "✅ Working Directory: $PWD"
+          ls -la
+          ls -la testing_data || echo "❌ testing_data NOT FOUND"
+
       - name: 🐳 Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      
       - name: ⚙️ Build & run using Docker Compose
         run: |
           docker-compose down --volumes --remove-orphans
           docker-compose up --build --abort-on-container-exit
-
